### ISSUE TITLE
Css not loading 

### ISSUE THREAD

**Issue by iamVP7** [brave/chromium#11]
In Brave Android CSS is not loading in my blog http://iamvp7.github.io 

I am using 
- Android version (4.0, 5.0, ...?): 7.0 
- Brave Version: 54.0.2795.0

Steps to Reproduce
- Open Brave
- Visit http://iamvp7.github.io

When the Shield is Down, then CSS loads properly.

@SergeyZhukovsky  helped to reproduce it.

**Comment by SergeyZhukovsky** [comment]
It was fixed here
https://github.com/brave/chromium/commit/94405c33b6f81a16da881032978ce92480e9dab2
