### ISSUE TITLE
Brave Keeps Stopping

### ISSUE THREAD

**Issue by iamVP7** [brave/chromium#13]
Open the [medium post]( https://medium.com/product-hunt/the-44-most-loved-products-launched-in-summer-2016-deaa36125316) in Medium Android application

Click on the Title like **Ok Google**

The  a pop up saying **Brave Keeps Stopping** comes. 

Android version (4.0, 5.0, ...?): 7.0 in Nexus 6p
Brave Version: 54.0.2795.0

![photo_2016-09-08_23-47-43](https://cloud.githubusercontent.com/assets/3106852/18361237/b8d4b590-761e-11e6-8686-2803d3267f5b.jpg)

**Comment by SergeyZhukovsky** [comment]
That was fixed.
