### ISSUE TITLE
TNW logo not dispalyed

### ISSUE THREAD

**Issue by iamVP7** [brave/chromium#16]
![screenshot_20160915-033425](https://cloud.githubusercontent.com/assets/3106852/18615321/07422fce-7dc1-11e6-948c-92ad124d12f8.png)

Android version (4.0, 5.0, ...?): 7.0 in Nexus 6p
Brave Version: 54.0.2795.0

But when shield is switched off it works.

Verified by @SergeyZhukovsky

**Comment by SergeyZhukovsky** [comment]
It was fixed here
https://github.com/brave/chromium/commit/94405c33b6f81a16da881032978ce92480e9dab2
