### ISSUE TITLE
Unexpected error on starting

### ISSUE THREAD

**Issue by luixxiul** [brave/chromium#26]
On JB 4.1.1 I got this error: 

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/19135853/d6f9af6e-8ba2-11e6-9968-4f5f0dc43fea.png)

This was confirmed by @SergeyZhukovsky too.

**Comment by SergeyZhukovsky** [comment]
Hi @luixxiul. Fixed it in the latest version
https://github.com/brave/chromium/releases/tag/v1.0.0beta1

**Comment by Diliz** [comment]
Hello! Seems the problem is back! :/ On Android x86 on a zenfone 2 since the last update fromage the play store :/

I can't launch brave anymore actually :(

**Comment by Diliz** [comment]
Ok, seems like if I install the x86 version you released on github there's no problem, but got it on the play store release dunno why...

**Comment by SergeyZhukovsky** [comment]
Yes, you are right @Diliz .
For some reason Google play store delayed with x86 update and pushes arm for everyone. We are going to update x86 first on next release and after that arm. For now you can download it manually here https://github.com/brave/browser-android-tabs/releases/download/v1.0.7/Bravex86.apk

**Comment by Diliz** [comment]
Yep yep, already did, thanks for the quick reply! :)

Merry Christmas and Happy new year all ^^

**Comment by SergeyZhukovsky** [comment]
Great, it is live on Play Market also now. Enjoy!
Merry Christmas and Happy New Year!
