### ISSUE TITLE
User Agent Detected wrongly as Chrome by Twitter

### ISSUE THREAD

**Issue by iamVP7** [brave/chromium#27]
- I am using Brave for Android.
- I logged into my twitter account
- It sent me a mail with subject "New login to Twitter from Chrome on Android"

**Expected Behavior**
- It sent me a mail with subject **"New login to Twitter from Brave on Android"**

Brave Version: 54.0.2795.0
OS : Android 7.0.0
Device : Nexus 6p Build / NBD90X

**Comment by SergeyZhukovsky** [comment]
We want to keep that for now.
