### ISSUE TITLE
Ad's not blocked on mobile site

### ISSUE THREAD

**Issue by srirambv** [brave/chromium#29]
~~Ad's not blocked on 9gag.com on mobile site. Select request desktop version ad's are blocked.~~

Edit : Ad's not blocked on mobile sites

![img-20161010-wa0024](https://cloud.githubusercontent.com/assets/17010094/19235600/5638b6d8-8f10-11e6-8251-645d009f9990.jpg)

**Comment by SergeyZhukovsky** [comment]
It works fine for me on stable version. Could you try the latest please? 
https://github.com/brave/chromium/releases/tag/v1.0.0beta1

**Comment by srirambv** [comment]
Checked with the stable version. Working as expected. Closing the issue
