### ISSUE TITLE
Infinite redirect on www.vice.com

### ISSUE THREAD

**Issue by bbondy** [brave/chromium#38]
vice.com redirects from https: to http:
I think we redirect from http: to https:

It looks like our Android browser fails on loading that page with too many redirects.
It works fine on laptop though.

/cc @diracdeltas in case she has ideas of what the bug is in the android implementation, or maybe android needs a list update?

/cc @SergeyZhukovsky

**Comment by SergeyZhukovsky** [comment]
It is a nice website to test endless redirect to http. I missed that as I couldn't find any way to test it. Correcting it now.

**Comment by SergeyZhukovsky** [comment]
Fixed it here
https://github.com/brave/chromium/commit/eb545519966c00512703e4149848d5b558bec0d8

**Comment by bbondy** [comment]
Shannon says thanks :) She landed on the site randomly.
